### ISSUE TITLE
Port features from tslearn

### ISSUE THREAD

**Issue by Roh-codeur** [baggepinnen/DynamicAxisWarping.jl#43]
Hi

its wonderful library, thanks for putting it together. I, especially, like the graphs.

I come from Python background, still learning Julia. do you think we could look at porting some of the features from:
https://tslearn.readthedocs.io/en/stable/auto_examples/index.html

thanks
Rohit

**Comment by baggepinnen** [comment]
Hello and thanks for your kind words 😊
Many of the features listed on that link are already available here. If there's some feature you're missing, I'm sure it could fit in here if it's related to dynamic time warping, otherwise it might fit into MatrixProfile.jl
