### ISSUE TITLE
Multi-thread version of dbaclust

### ISSUE THREAD

**Issue by paciops** [baggepinnen/DynamicAxisWarping.jl#44]
From the docstring of `dbaclust` I see  `n_jobs`  but it is not implemented, could it be useful if I propose a multi-thread implementation of `dbaclust` and `dbaclust_single` where all the distpath are calculated in paralle?

**Comment by baggepinnen** [comment]
Hey! It's probably an oversight on my behalf. A multithreaded implementation could be very useful 😃

**Comment by paciops** [comment]
Perfect,  I will try do my best, it's my first contribution :)

**Comment by paciops** [comment]
I wrote a first basic [implementation](https://github.com/paciops/DynamicAxisWarping.jl/commit/29ae48b75e708a029088a152c7a37fe866f7ca76) but I don't understand how to run test, how should I do?

**Comment by baggepinnen** [comment]
Nice, welcome to the open-source world! I think your editor has applied some automatic formatting of the code causing the diff to be very large. It's generally ill advised to apply formatting when you submit a PR since that makes actual changes very hard to track.

If you have checked out the package for development using `pkg> dev DynamicAxisWarping` (recommended), you run the test using `Pkg.test("DynamicAxisWarping")`

**Comment by paciops** [comment]
Okay so I found out that to test the package I have to be outside of the folder, so now I know how to test.
I wrote one to test the speedup between the mono core and the multi core and I reformatted according to the previous format becc03c7aee90358b8ebf2348f74c19d4c3eeceb

Now I think that I could also improve `dbaclust_initial_centers`

**Comment by baggepinnen** [comment]
That looks very reasonable, here's the diff for future reference
https://github.com/baggepinnen/DynamicAxisWarping.jl/compare/master...paciops:multithread

I think what remains to do is to
- Have some tests that it computes something reasonable.
- The threaded tests should run even if `Threads.nthreads() == 1`. `@threads` works even in this case, it's just not threaded.
- We should not test the timing, e.g., `@test mean(result[1].times) > mean(result[2].times) `. When running on CI, we can not guarantee that the CI machine is not busy with other things when running the threaded tests and this can lead to spurious failures.
- Remove the BenchmarkTools dependency.
- We should not call the keyword `n_jobs` if it does not control the number of threads. Perhaps `threaded=true` is a better choice of word?

**Comment by paciops** [comment]
Okay so I changed `n_jobs` to `theaded` and changed the type from `Int` to `Bool`, I think it is a good choice.
About the test if we don't want to test the performance because of the CI machine, we could just run a test as in dbaclust with FastDTW and BenchmarkTools could be removed.

**Comment by paciops** [comment]
So I changed the test to work even if there is only one core and BenchmarkTools is removed.
I also changed the Progress in dbaclust to work over the for loop of `n_init` because using the progress of `dbaclust_single` with multiple threads could give a confusing output.
Is there anything else that I should change?

**Comment by baggepinnen** [comment]
Sounds good 😃 the next step is to open a pull request!
