### ISSUE TITLE
Cite this package

### ISSUE THREAD

**Issue by paciops** [baggepinnen/DynamicAxisWarping.jl#47]
I am writing my bachelor thesis and I would like to cite this package because I used it to calculate the distance matrix of time series that I am working with.
Could I insert something like this ?
```
@software{DynamicAxisWarping,
  author = {Fredrik, Bagge, Carlson},
  title = {{Dynamic Axis Warping}},
  url = {https://github.com/baggepinnen/DynamicAxisWarping.jl},
  version = {0.4.11},
  year = {2020}
}

```

**Comment by baggepinnen** [comment]
Hello @paciops, I'm glad you've found the package useful :) 
I believe the correct formatting of the author name in bibtex would be `{Bagge Carlson, Fredrik}` and the title should be `{DynamicAxisWarping.jl}`, otherwise the reference looks good!
