### ISSUE TITLE
Plots.jl should not be a dependence

### ISSUE THREAD

**Issue by okartal** [baggepinnen/DynamicAxisWarping.jl#57]
When using DynamicAxisWarping, it introduces dependencies on Plots.jl

**Comment by shayandavoodii** [comment]
Because it introduces [`dtwplot`](https://docs.juliahub.com/DynamicAxisWarping/I7QEd/0.4.16/autodocs/#DynamicAxisWarping.dtwplot) and other plotting functions. I do not know why this issue is still open while the maintainer is online these days.

**Comment by baggepinnen** [comment]
> I do not know why this issue is still open while the maintainer is online these days.

Feel free to submit a PR that fixes the issue if you find it urgent. I have other engagements that are currently taking priority.

**Comment by shayandavoodii** [comment]
@baggepinnen, You did not get my point. I was answering @okartal , explaining why you've used Plots in the dependencies! Anyway, good luck with your engagements!

**Comment by baggepinnen** [comment]
Thanks ;) OP is likely correct in that RecipesBase could be used instead of Plots though
