### ISSUE TITLE
[Question] How to measure the similarity between two time series using the package?

### ISSUE THREAD

**Issue by shayandavoodii** [baggepinnen/DynamicAxisWarping.jl#59]
Hi,
I was looking for a package that provides DTW in Julia and I think the only active repository is this repo. I saw you've provided brief documentation about [Find a short pattern in a long time series](https://docs.juliahub.com/DynamicAxisWarping/I7QEd/0.4.16/#Find-a-short-pattern-in-a-long-time-series). Unfortunately I'm not an expert in the field of Signal Processing, hence I do not know what do you mean by *"a short pattern"*. Anyway, I want to see whether one can use this package to assess the similarity of two time series. If yes, I would appreciate it if you could provide an example of achieving it.
Thank you

**Comment by baggepinnen** [comment]
This package computes the dtw semi metric, if that's the "similarity" you are after then you are in luck, just call
```julia
cost, i1, i2 = dtw(a,b)
```
