### ISSUE TITLE
Dataset function is inactive

### ISSUE THREAD

**Issue by danareu** [baggepinnen/DynamicAxisWarping.jl#65]
DynamicAxisWarping.Datasets.download_ucr() yields:

UndefVarError: `download_ucr` not defined

It seems that this function is not active any more.

**Comment by baggepinnen** [comment]
Thanks for the issue, that's right, it has been removed. You can still see it here
https://github.com/baggepinnen/DynamicAxisWarping.jl/blob/6fe047d1568a197af82a9a0747e15ca101ecfd5c/src/datasets/ucr_datasets.jl
but IIRC it had some bugs.

**Comment by danareu** [comment]
Okay, are there any other datasets provided to test DynamicAxisWarping.jl?

**Comment by baggepinnen** [comment]
Not really, apart from what you see in the readme and in the test files. As a potential user, don't you have a dataset you are ultimately interested in performing inference on?

**Comment by baggepinnen** [comment]
You can also just download datasets yourself from here
https://www.cs.ucr.edu/~eamonn/time_series_data/

**Comment by baggepinnen** [comment]
I removed the function from the package in https://github.com/baggepinnen/DynamicAxisWarping.jl/commit/f8f7a3f8a4568f0230614070e3927310ff18bfc9 to not confuse users anymore
