### ISSUE TITLE
Centers in dbaclust

### ISSUE THREAD

**Issue by jaksle** [baggepinnen/DynamicAxisWarping.jl#67]
I am trying to perform clustering based on DTW and I wanted to check `dbaclust` method here, I also need cluster (bary)centers. But the ones returned by `dbaclust` looked wrong. So I used method `dba` on the obtained clusters with the same `DTW(250)` as `dbaclust`, the result was different  and much more sensible. I am at loss here. What are those centers if not dba barycenters?

**Comment by baggepinnen** [comment]
Have you seen the warning in the readme, and the links therein?
https://github.com/baggepinnen/DynamicAxisWarping.jl?tab=readme-ov-file#clustering-and-barycenter-averaging

DBA is known not to be a great algorithm at producing barycenters. See the example under https://github.com/baggepinnen/DynamicAxisWarping.jl?tab=readme-ov-file#differentiable-soft-dtw for how to produce much nicer barycenters

**Comment by jaksle** [comment]
But this is not my question. My question is if this even is dba.

**Comment by baggepinnen** [comment]
The `dba` iteration code is called from within `dbaclust`, but with a smaller default number of iterations than the default of calling `dba` directly

**Comment by jaksle** [comment]
Oh, this must be the source of the difference. Thank you!
